import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import profilePic from "../../public/images/profile/developer-pic-1.png";
import AnimatedText from "@/components/AnimatedText";
import Link from 'next/link'
import { LinkArrow } from "@/components/Icons";
import HireMe from "@/components/HireMe";
import lightBulb from '../../public/images/svgs/miscellaneous_icons_1.svg'


export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      
      <main className="flex items-center text-dark w-full min-h-screen dark:text-light sm:overflow-hiiden">
        <Layout classname="pt-0 md:pt-16 sm:pt-8">
          <div className="flex items-center justify-between w-full lg:flex-col">
            <div className="w-1/2 md:w-full">
              <Image
                src={profilePic}
                alt="Profile Image"
                className="w-full  h-auto lg:hidden md:inline-block sm:w-full "
                priority={true}
                sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 50vw"
              ></Image>
            </div>
            <div className="w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center">
              <AnimatedText text="Hi, I am Mohammed Serif Turning Vision Into Reality. " className="!text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl"/>
              {/* <AnimatedText text=" With Code And Design." className="!text-6xl text-left"/> */}
              <p className="my-4 text-base font-medium md:text-sm sm:text-xs">
                As a skilled full-stack developer, I am dedicated to turning
                ideas into innovative web applications. Explore my latest
                projects and articles, showcasing my expertise in React.js and
                web development.
              </p>
              <div className="flex items-center self-start mt-2 gap-3 lg:self-center">
                <Link href='/dummy.pdf' target={"_blank"} className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark hover:transition duration-500 ease-in-out dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light md:p-2 md:px-4 md:text-base" download={true}>Resume <LinkArrow className={"ml-1 w-6"}/></Link>
                
                <Link href='mailto:mdserif1998@gmail.com' target={"_blank"} className="flex items-center bg-light text-dark p-2.5 px-6 py-2.5 rounded-lg text-lg  border-2 font-semibold border-solid border-dark hover:text-light hover:bg-dark hover:transition duration-500 ease-in-out hover:border-transparent hover:dark:border-light md:p-2 md:px-4 md:text-base ">Contact</Link>
              </div>
            </div>
          </div>
        </Layout>

        <HireMe/>

        <div className="absolute right-8 bottom-8 inline-block w-24">
          <Image src={lightBulb} alt='lightBulb' className="w-full h-auto md:hidden"></Image>
        </div>

      </main>
    </>
  );
}
